### ISSUE TITLE
Failed to convert String to JsonObject in GBContext.java class

### ISSUE THREAD

**Issue by WemyVieira** [growthbook/growthbook-sdk-java#14]
![image](https://user-images.githubusercontent.com/24321524/206746364-7e6a724b-d215-4185-b6b7-5231074d25fe.png)

![image](https://user-images.githubusercontent.com/24321524/206746492-46810fed-ef19-407a-9100-6b39681f9bc1.png)

![image](https://user-images.githubusercontent.com/24321524/206747190-f6ea1147-d339-4c5c-896a-448edd1f8596.png)

**Comment by tinahollygb** [comment]
@WemyVieira thanks for the submission. Is this issue still happening? 

I've added a unit test [here](https://github.com/growthbook/growthbook-sdk-java/compare/bug/14-failed-conversion) to try to reproduce your issue. It appears to be passing with data similar to yours, so based on what I see in the screenshots, I'm not able to reproduce the issue with the features JSON string and attributes JSON string you provided.

Can you copy/paste (in text, not in image) the following:

- your exact string for the JSON you're using
- your dependencies in your gradle or pom file
    - It looks like your project is using the same version of Gson which should be OK
- version of Java
- any other information you may think could be helpful

Are you able to create a sample app where this error is reproducible?

**Comment by tinahollygb** [comment]
Can you also share your Gson configuration? While we are using different instances of Gson and the GsonBuilder, I wanted to make sure your configuration wasn't being applied to ours. For example, one configuration option that could be problematic is if you called [`GsonBuilder.excludeFieldsWithoutExposeAnnotation()`](https://www.javadoc.io/static/com.google.code.gson/gson/2.6.2/com/google/gson/GsonBuilder.html#excludeFieldsWithoutExposeAnnotation--) on your GsonBuilder but that configuration should only impact your GsonBuilder instance and not ours.

**Comment by tinahollygb** [comment]
@WemyVieira have you had a chance to explore this further? Are you still experiencing the problem?

**Comment by tinahollygb** [comment]
Closing as stale. If you can provide a way to reproduce this, please share and feel free to re-open.
