### ISSUE TITLE
Add Java doc for Lombok-generated methods

### ISSUE THREAD

**Issue by tinahollygb** [growthbook/growthbook-sdk-java#4]
Unfortunately, getting the Java docs picked up for the Lombok-generated methods is going to be a bit of error. Lombok offers [Delombok](https://projectlombok.org/features/delombok), a tool that you can use to de-Lombok. I've read that this can help with the Java doc generation. 

For more info, see https://github.com/growthbook/growthbook-sdk-java/pull/3

**Comment by Bohdan-Kim** [comment]
The [pull request](https://github.com/growthbook/growthbook-sdk-java/pull/61) was created according to this issue.
