### ISSUE TITLE
isOn() does not return info whether the feature is enabled

### ISSUE THREAD

**Issue by lsergio** [growthbook/growthbook-sdk-java#41]
Per the sdk documentation:
![image](https://github.com/growthbook/growthbook-sdk-java/assets/545261/f41a821e-8cf0-41f2-ab18-72b4f23af850)

isOn() should tell me whether is feature is enabled.
But instead it inspects the value of the feature and returns true if the value is a positive number, a non-empty string or true.

So, if I have a feature that is enabled on any environment, but the default value is 0 per my business rules, the sdk will return false for isOn.
If this is intentional, we might change the docs, and maybe add a isEnabled(featureName) method.

**Comment by lsergio** [comment]
In my sceario, I'm trying to check if these toggles are on or off, regardless of the feature value:
![image](https://github.com/growthbook/growthbook-sdk-java/assets/545261/c0cbde28-723a-4737-8c61-0af8b6b0a6fc)

So for now I inspected the features json manually instead of using the sdk.

**Comment by vazarkevych** [comment]
Hi, we fix this issue in this [pr] (https://github.com/growthbook/growthbook-sdk-java/pull/62). After it is merged, it will be included in the next release.

**Comment by vazarkevych** [comment]
Hi, we have fixed this issue here is pull request for it

**Comment by vazarkevych** [comment]
Hi, we have fixed this issue here is [https://github.com/growthbook/growthbook-sdk-java/pull/65](pull request)

**Comment by vazarkevych** [comment]
Hi, we have fixed this issue. Here is a pull request for it  (https://github.com/growthbook/growthbook-sdk-java/pull/65).
