### ISSUE TITLE
Request to Support Schrödinger State Evaluation in Java SDK

### ISSUE THREAD

**Issue by ashenp** [growthbook/growthbook-sdk-java#47]
Currently, it appears that the SDK does not support the evaluation of the Schrödinger state. This is a very important feature for many users, particularly those working in quantum computing or similar fields. The ability to evaluate the Schrödinger state is crucial to accurately model and understand quantum systems.

I understand that implementing this feature might require substantial work, but I believe it would be a valuable contribution to the SDK. It would not only extend the current capabilities of the SDK but also make it more appealing to a wider audience.

I hope you will consider this request. I am looking forward to any feedback or thoughts you might have on this.

**Comment by Bohdan-Kim** [comment]
Hello @ashenp!

From my point of view if we add the evaluation of the Schrödinger state, we will be obligated to add the same to all others SDKs (Kotlin, Swift, Dart etc.)
First of all the method of the evaluation of the Schrödinger state should appear in [docs](https://docs.growthbook.io/lib/build-your-own) and then the developers of the SDKs will implement this feature.

It seems like to add @Auz and @jdorn to the discussion is appropriate here.
