### ISSUE TITLE
SDK throws exceptions for serialized null values

### ISSUE THREAD

**Issue by nnusse** [growthbook/growthbook-sdk-java#49]
Hello, i'm Norman, Software Engineer at idealo and i would like to draw your attention to a problem in this library. One of our applications printed some unexpected exception stack traces after we turned on one of our A/B tests. The problem is that the `ConditionEvaluator` is not able to handle serialized null values for all possible operators (e.g. $in, $nin, etc. ). This is a problem for us, because the evaluation process stops and our log-shipper expects a specific format for all messages/text that will be printed to stdout/stderr.

We would like to offer a possible fix for that use case (Pull Request #48), that should make the `ConditionEvaluator` more robust. 
Feedback is highly appreciated and welcome!
 
Best regards,
Norman on behalf of idealo

**Comment by vazarkevych** [comment]
Issue closed due to pull request successfully approved and merged.
