### ISSUE TITLE
Usage timeframe

### ISSUE THREAD

**Issue by nkdevirl** [growthbook/growthbook-sdk-java#5]
Not an Issue. Just evaluating growth-book for a React and Spring based application.
Just curious on when this might be ready for use?

**Comment by tinahollygb** [comment]
@nkdevirl thanks for your excitement about this SDK. We're happy to mention that we just released our first version today, so it is very new but available to use now.

You can read the docs for more information: https://docs.growthbook.io/lib/java

At the bottom of the docs page, there's also links to working example projects in Spring and Android, as well as a link to the JavaDoc class docs.

Let us know if you have any feedback, thanks!
