### ISSUE TITLE
SDK Java doesn't reconnect when using SSE

### ISSUE THREAD

**Issue by mvsmasiero** [growthbook/growthbook-sdk-java#52]
I have a scenario where I use the GrowthBook proxy and use the Java SDK's GBFeaturesRepository class using the SERVER_SENT_EVENTS strategy.

When the application loses connection with the proxy (the proxy may restart or there is a network issue) the GBFeaturesRepository doesn't reconnect to the proxy.

**Comment by Bohdan-Kim** [comment]
Hello @mvsmasiero!
I suppose connection is stable for 5 minutes and after that connection is being closed.
Is connection lasting, for example, 30min better for you?

**Comment by Bohdan-Kim** [comment]
It seems like the cause why it doesn't reconnect is Proxy off. When Backend is working `GBFeaturesRepository` successfully reconnects.
![image](https://github.com/growthbook/growthbook-sdk-java/assets/135710078/45f3b200-b93f-4cd3-b03c-6b07d52f2ae0)
![image](https://github.com/growthbook/growthbook-sdk-java/assets/135710078/5e9e8a08-fe9e-4b5a-90a8-753de9f22896)

**Comment by mvsmasiero** [comment]
Hello @Bohdan-Kim 

When the Java application loses connection to GB Proxy, this method on the GBFeatureRepository is called:

![image](https://github.com/growthbook/growthbook-sdk-java/assets/2656329/55b3a569-b930-4e01-8065-f6144ad7e7d2)

When the connectivity issue is fixed, the application only connects to GBProxy after restarting the application.

**Comment by Bohdan-Kim** [comment]
It seems like we should make changes to the sources in order to handle this.

**Comment by Bohdan-Kim** [comment]
The [pull request](https://github.com/growthbook/growthbook-sdk-java/pull/55) was created according on the issue. We expect that calling `initialize()` method with `retryOnFailure` = `true` will lead to execution of this block:
![image](https://github.com/growthbook/growthbook-sdk-java/assets/135710078/54098644-32fd-43bc-9adf-e5028179643e)

**Comment by mvsmasiero** [comment]
Hello @Bohdan-Kim , I've tested the solution.

With this solution, the Java application reconnects to GB Proxy successfully, but I've found a problem: if a flag is changed before the application reconnects, that change is not reflected.

I tested this change to fix it. What do you think?

![image](https://github.com/growthbook/growthbook-sdk-java/assets/2656329/1673812e-096f-475b-93e0-7f50b48218fe)

**Comment by Bohdan-Kim** [comment]
``if a flag is changed before the application reconnects``
How is it possible that the flag can be changed? Calling `initialize()` method the second time? The connection already established. Why calling the `initialize()` method again is needed?

**Comment by mvsmasiero** [comment]
I think the chances of this happening are low, but I believe it is important to evaluate this possibility. For example: The GB Proxy may be down and the Product Owner does not know about it and activates some Flag or makes some other change.

**Comment by Bohdan-Kim** [comment]
Ok
