### ISSUE TITLE
JsonObject vs. JsonPrimitive error

### ISSUE THREAD

**Issue by august-growthbook** [growthbook/growthbook-sdk-java#57]
Posting this on behalf of a customer. 

It looks like we're getting an error while parsing a JSON object containing the features flags and/or initializing the client - ­[code](https://github.com/growthbook/growthbook-sdk-java/blob/main/lib/src/main/java/growthbook/sdk/java/GBFeaturesRepository.java#L320-L321)

I think the line Expected a `com.google.gson.JsonObject` but was `com.google.gson.JsonPrimitive; at path $` means that the root object (at `$`) wasn't actually an object, but we thought it could also mean that a particular feature flag contained invalid JSON

For reference, we're using a Java SDK Connection.

![Screenshot 2024-05-09 at 11 29 38 AM](https://github.com/growthbook/growthbook-sdk-java/assets/144278508/2fe63275-7d3a-45db-8204-4f5255f780a9)

Any additional detail / explanation would help

Thanks!

**Comment by Bohdan-Kim** [comment]
Hello, August!
Could you ask client to share client key (API key) in private messages? We would see response from Backend then.

**Comment by vazarkevych** [comment]
Hi, @august-growthbook. Do we have any updates on that issue?

**Comment by vazarkevych** [comment]
Hi, we've made many changes to HttpClient, so we hope this issue won't occur anymore in the latest version of the SDK.
