### ISSUE TITLE
Release 0.9.3 produces a lot of messages to STDOUT

### ISSUE THREAD

**Issue by nnusse** [growthbook/growthbook-sdk-java#64]
Hello, 

we want to inform you that the latest release **0.9.3** introduced a  `System.out.println()` statement that is producing a lot of logs within our systems. 

I refer to this line: [FeatureEvaluator#L52](https://github.com/growthbook/growthbook-sdk-java/blob/main/lib/src/main/java/growthbook/sdk/java/FeatureEvaluator.java#L52)

**Comment by Bohdan-Kim** [comment]
Hello,

We pushed [fix](https://github.com/growthbook/growthbook-sdk-java/pull/63/commits/024420c6759be759f5678a475736cf255dbb2eea) in release/0.9.4 branch.
Seems like it should help you:
```
dependencies {
	        implementation 'com.github.growthbook:growthbook-sdk-java:release~0.9.4-SNAPSHOT'
}
```
