### ISSUE TITLE
FeatureEvaluator pollutes Logs

### ISSUE THREAD

**Issue by tde-desc** [growthbook/growthbook-sdk-java#67]
I am referring to this line:

`System.out.println("evaluateFeature: circular dependency detected:");
`

in `FeatureEvaluator` since version 0.9.3. Of which use is that logging? At least it would make sense to use logback or something similar, so that it is possible to silence those logs.

**Comment by Bohdan-Kim** [comment]
Hello,

We pushed [fix](https://github.com/growthbook/growthbook-sdk-java/pull/63/commits/024420c6759be759f5678a475736cf255dbb2eea) in release/0.9.4 branch.
Seems like it should help you:
```
dependencies {
	        implementation 'com.github.growthbook:growthbook-sdk-java:release~0.9.4-SNAPSHOT'
}
```

**Comment by tde-desc** [comment]
Thank you!
