### ISSUE TITLE
the new dependency 'com.github.tony19:logback-android:3.0.0' breaks builds

### ISSUE THREAD

**Issue by Jenny-at-idealo** [growthbook/growthbook-sdk-java#68]
Hey there,

the update to your sdk version 0.9.4 breaks our build because the new dependency com.github.tony19:logback-android:3.0.0 is  not included in your released library and we get forced to add it to our own project dependencies despite we don't need it ourselves.
Also i don't see a usage in your code.

Is it planned to be like that? What's the purpose of the dependency?

Thanks for the clarification!

**Comment by vazarkevych** [comment]
@Jenny-at-idealo, we just checked the issue you mentioned, and everything is working. Did you try invalidating the cache, cleaning, or rebuilding the project? We need this dependency for viewing logs on Android.

**Comment by Jenny-at-idealo** [comment]
@vazarkevych : we use the growthbook-sdk library in a java spring-boot application that is build with maven. 
Now with 0.9.4 we have to add the _com.github.tony19:logback-android:3.0.0_ dependency to our pom.xml because the growthbook-sdk needs it and otherwise it breaks our build.

I was wondering if the growthbook-sdk release could ship the com.github.tony19:logback-android:3.0.0 with itself, which means not forcing the users of the growthbook-sdk library to **also** add an additional dependency.

**Comment by Bohdan-Kim** [comment]
Hello @Jenny-at-idealo!
We removed `logback-android` dependency in `issues/68` branch.
Try please this:
```
	dependencies {
	        implementation 'com.github.growthbook:growthbook-sdk-java:issues~68-SNAPSHOT'
	}
```

**Comment by Jenny-at-idealo** [comment]
Thanks @Bohdan-Kim , we will try and get back to you!

**Comment by Bohdan-Kim** [comment]
```
	<dependency>
	    <groupId>com.github.growthbook</groupId>
	    <artifactId>growthbook-sdk-java</artifactId>
	    <version>issues~68-SNAPSHOT</version>
	</dependency>
```

**Comment by Jenny-at-idealo** [comment]
It's fine @Bohdan-Kim . Thanks for the fast fix!

**Comment by Bohdan-Kim** [comment]
Release version 0.9.5 is available on jitpack.io
