### ISSUE TITLE
Add support for reusing `GrowthBook` object

### ISSUE THREAD

**Issue by buterbread1996** [growthbook/growthbook-sdk-java#81]
The current `growthbook.sdk.java.GrowthBook` implementation can't be used like bean in Spring, because it reuse a `growthbook.sdk.java.FeatureEvaluator#featureEvalContext` without clearing.
So in the first call `growthBook.isOn(featureKey)` returns right value, but in the next calls it returns `false` value **always**, because all calls (expect the first one) are interpretered like "circular dependency".
The `featureEvalContext` is reseted only by `goOutFromCircularLoop` method that is called only in one place - when the force rule is applied.

I don't know what logic did you want to implement, but current logic looks like some strange.

**Comment by Bohdan-Kim** [comment]
Hello @buterbread1996 !
Thanks for reporting this issue.
We've changed the logic of entering into circular loop.

Could you please try `issues/81` SNAPSHOT?
https://jitpack.io/#growthbook/growthbook-sdk-java/issues~81-SNAPSHOT

**Comment by vazarkevych** [comment]
Hi, @buterbread1996. Did you try that SNAPSHOT?

**Comment by buterbread1996** [comment]
@vazarkevych @Bohdan-Kim
I am sorry for the late answer. I checked 0.9.8 version and it works great.
Thank you very much for the quick fix!
