### ISSUE TITLE
Feature Evaluator not evaluating experiments

### ISSUE THREAD

**Issue by fabianmarinog** [growthbook/growthbook-sdk-java#87]
We recently noticed that SDK version 0.9.3+ has caused non-deterministic responses when calling `growthBook.evalFeature(featureKey, Object.class)`. When experiment rules are configured, the feature result will always be null and the default value will be returned, leaving us no actual 50/50 AB tests. We had to downgrade to version 0.9.2 to get back the correct featureResults.  Forced rules work fine, causing us a hard time detecting the cause of the issue. 

We expect that `evalFeature` method returns correct featureResults when used for experiment assignations. 

We specifically noticed that featureResult was null but sometimes `cyclicPrerequisite` was returned instead. What is the purpose of this [cyclicPrerequisite](https://github.com/growthbook/growthbook-sdk-java/blob/331c2a2faf201c8c7bfd0a3fb3d1211c4502c67b/lib/src/main/java/growthbook/sdk/java/FeatureResult.java#L43)?

**Comment by Bohdan-Kim** [comment]
Hello!
We are sorry we really had non-deterministic responses but we fixed our issue in this [pull request](https://github.com/growthbook/growthbook-sdk-java/pull/83).
Could you please try `0.9.8` version of GrowthBook Java SDK?

	<dependency>
	    <groupId>com.github.growthbook</groupId>
	    <artifactId>growthbook-sdk-java</artifactId>
	    <version>0.9.8</version>
	</dependency>

**Comment by vazarkevych** [comment]
Hi, @fabianmarinog. Did you try to use 0.9.8 version of GrowthBook Java SDK?

**Comment by fabianmarinog** [comment]
hi @vazarkevych, yeap everything works now with 0.9.8.

**Comment by vazarkevych** [comment]
Great, thank you for the feedback.
