### ISSUE TITLE
`ClassCastException` while using Number feature and trying to use it as a double.

### ISSUE THREAD

**Issue by gaurav-rana** [growthbook/growthbook-sdk-java#89]
## Description:
We want to define a double feature in growthbook, given GB only has a way to define Number feature, we created a Number feature. Now, if we create a Number feature without any decimal points (i.e. 17.00) then growthbook featureJson contains 17 instead of 17.00 and Java SDK thinks it's a Long Feature and throws exception if we use growthbook.evalFeature API

### Steps to reproduce:
1. Create a Number feature in growthbook UI
![Screenshot 2024-07-22 at 2 31 53 PM](https://github.com/user-attachments/assets/c7502648-a376-4e5d-8b51-71876df9a867)
2. Now, in the Java SDK, try to use this feature using the `evalFeature` API
`FeatureResult<Double> result = growthBook.evalFeature("TestNumber", Double.class);
`
and it throws an exception
`Exception in thread "main" java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Double (java.lang.Long and java.lang.Double are in module java.base of loader 'bootstrap')
`
3. Instead, if we use `public Float getFeatureValue(String featureKey, Float defaultValue)` API then it doesn't throw the exception.

**Comment by Bohdan-Kim** [comment]
Hello, @gaurav-rana!
We see your concern. We also had set the value of `TestNumber` feature to `17.00` but we see that in endpoint response the feature value is sent as `17`:
https://cdn.growthbook.io/api/features/sdk-3e06aog6O1Mp6Ir
![image](https://github.com/user-attachments/assets/ba5c2fb5-818a-41a9-9091-de463329888f)

**Comment by Bohdan-Kim** [comment]
So, the user of the GB Console is seeing `17.00` in his console but the endpoint sends `17`. It looks like the issue on Backend side but `17.00` really can be casted to `17` no data loss here.

**Comment by Bohdan-Kim** [comment]
The data is transferred in JSON format. [The JSON Standard ECMA-404](https://ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf) declares that: 
```
A JSON value can be an object, array, number, string, true, false, or null.
```
So, we don't see the separation on `Integer` and `Double` number types in JSON Standard, therefore we think that it is wrong to expect `Double` type from json value. Maybe using `FeatureResult<Number>` instead of `FeatureResult<Double>` will help:
```
FeatureResult<Number> result2 = subject.evalFeature("TestNumber", Number.class);
```

**Comment by gaurav-rana** [comment]
Yeah, It makes sense, Thanks for the response!
