### ISSUE TITLE
FeatureFetchException: CONFIGURATION_ERROR savedGroupsJsonElement fetch error code

### ISSUE THREAD

**Issue by vasilii-bolgar-tr** [growthbook/growthbook-sdk-java#92]
After upgrading to the newest version some of applications throw the next errors:

```
FeatureFetchException: CONFIGURATION_ERROR savedGroupsJsonElement fetch error code
```

```
FeatureFetchException: CONFIGURATION_ERROR encryptedSavedGroupsJsonElement fetch error code: encryptionKey provided but endpoint not encrypted
```

Probably this commit to be claimed - https://github.com/growthbook/growthbook-sdk-java/commit/a40b08813470b4053a61df39995e58c7d256e245#diff-27b41c802a65672520c674fa86e847a00271031eb193634b13cc7b18aeeae1a3R415-R421

**Comment by Bohdan-Kim** [comment]
Hello @vasilii-bolgar-tr!
Is the SDK literally throwing an exception or printing errors to logs?

**Comment by msdousti24** [comment]
Hi @Bohdan-Kim,

No it's just printing errors (like once per second). I tested and the functionality of GrowthBook is not impaired.

**Comment by Bohdan-Kim** [comment]
[The pull request](https://github.com/growthbook/growthbook-sdk-java/pull/93) was created according to this issue
