### ISSUE TITLE
java.lang.NoSuchMethodError(No static method forEach)

### ISSUE THREAD

**Issue by RevakoOA** [growthbook/growthbook-sdk-java#94]
Hi, we are using this library in the android kotlin project. We have tried the [kotlin version of the library](https://docs.growthbook.io/lib/kotlin) but it didn't satisfy us. Crashed quite a lot and was limited in configuration. So we switched to java version sdk and it would be great if you could make this small fix in this java version.

That's what we have in crashlytics:
```
Fatal Exception: java.lang.NoSuchMethodError
No static method forEach(Ljava/lang/Iterable;Lj$/util/function/Consumer;)V in class Lj$/lang/Iterable$-EL; or its super classes (declaration of 'j$.lang.Iterable$-EL' appears in /data/app/androidx.test.tools.crawler--hW9auAVx_MUnHM-VYSElQ==/base.apk!classes2.dex)
at
growthbook.sdk.java.GBFeaturesRepository.onRefreshSuccess (GBFeaturesRepository.java:7)
growthbook.sdk.java.GBFeaturesRepository.onResponseJson (GBFeaturesRepository.java:66)
growthbook.sdk.java.GBFeaturesRepository.onSuccess (GBFeaturesRepository.java:10)
growthbook.sdk.java.GBFeaturesRepository.fetchFeatures (GBFeaturesRepository.java:47)
growthbook.sdk.java.GBFeaturesRepository.initialize (GBFeaturesRepository.java:26)
```

In short, could you please switch using of forEach to the regular for loop in both `onRefreshSuccess` and `onRefreshFailed`.

We have this issue for 1 in 1000 users. Not that much, but it's quite annoying.
We used 'com.github.growthbook:growthbook-sdk-java:0.9.1' version but from what I see the latest 0.9.9 still contains this.

**Comment by Bohdan-Kim** [comment]
Hello, `forEach` method was replaced with regular `for` loop in [this pull request](https://github.com/growthbook/growthbook-sdk-java/pull/96)
